### ISSUE TITLE
Issues with Python 3.4

### ISSUE THREAD

**Issue by azyr** [Komnomnomnom/swigibpy#25]
Swigibpy has some minor issues with Python 3.4. Fixing it was quite easy, just replacing all instances of dict.iteritems() with dict.items() in swigibpy.py solved the problem. Will keep an eye out for other incompatibilities and report them here...

Can this fix be merged in the repository?

**Comment by Komnomnomnom** [comment]
Fixed by c142d2fc995814498007032ba6d91324ff6c6b44
