### ISSUE TITLE
Reconnection feature in TWSPoller

### ISSUE THREAD

**Issue by sandrinr** [Komnomnomnom/swigibpy#34]
Hi

I was unable to find an email address of yours on your Guthub page so I am contacting you through opening an issue.

Recently you committed a change introducing a reconnection feature into the TWSPoller thread. Looking at this change I find it to be pretty complicated and I am not entirely convinced whether it does even belong there. You are diverging from the functionality offered by the original IB library quite a bit with this change. Wouldn't it be better to keep the TWSPoller as simple as possible and refrain from changing IB library functions and move such functionality into a separate IB utility library?

I do not want to tell you how you have to shape your library ;-), so I asking you what are your plans regarding the TWSPoller thread? Do you want to keep it that way or even extend it? If yes, then I will probably maintain a fork with the previous version of this TWSPoller thread.

BTW: From reading the code right you will end up in an endless loop when disabling the auto-connect feature and loosing the connection to TWS.

Regards,
Raffaele

**Comment by bimbomix1** [comment]
Hi Raffaele, 
I don't understand. I never sent a change about TWSPoller. And sincerily now i don't know what is it 
i wanted to send a issue about the first page example. It doesn't work because i didn't found "swigibpy.EWrapperVerbose" In library .. but i i'm not an expert.. I just discovered this library yesterday. 
I'm a trader and a programmer so probabily i will use a lot.  Are you sure that i committed someting ? .. 

Are you italian ? Because your name sounds italian as my

**Comment by Komnomnomnom** [comment]
Thanks @sandrinr for the feedback. A public issue or mailing list is the best place for a design discussion imo. 

You could argue that the existence of `TWSPoller` is already diverging from the IB library functionality quite a bit but to be clear my philosophy with `swigibpy` is:

1. keep it as simple and bare-bones as possible. This means avoiding augmenting or enhancing the C++ API methods and classes as much as possible.
2. if additional functionality is introduced it should be optional and / or reversible. This includes C++ patches that make it work better with SWIG and / or Python.
3. however, any additional supporting functionality that makes the library more usable and easier to deal with 'out of the box' is welcome (the batteries included Python philosophy).

Point 3 is the motivation for the poller, the default error handling and the reconnection feature. They are all of course optional and easy to replace, also note the auto-reconnection is **disabled by default**. 

To clear up what might be a few misconceptions. 
 - A poll thread or poll loop is always in a sense indefinite. It exists and loops as long as a program is interested in sending or receiving messages. There is nothing wrong with this. 
 - The reconnection feature is opt-in and disabled by default. This is motivated partly by backwards compatibility but also I think it is something that is better to be explicitly enabled by the user so they are aware of it.

So (apart from some improved error handling behaviour) the current code in master does not change the high-level, default behaviour of the poll thread. The only difference is that the poll thread persists across auto reconnections. As before if a user explicitly disconnects (by calling `eDisconnect`) the poll thread is still stopped and destroyed, and a new one created if a connection is restored (by calling `eConnect`).

I do not have any current plans for the poller, that may or may not change. I'm always open to bug fixes and suggestions for improvement though!

I welcome any pull request or discussion or their own merits and would prefer to win you over and keep you on board. This is open source however so you are free to use, modify, fork and redistribute my code as you wish.

**Comment by sandrinr** [comment]
Hi

Thanks for your explanation and please excuse my late response. From my side there is no need to keep this issue open.

Regards,
Raffaele

**Comment by Komnomnomnom** [comment]
Thanks @sandrinr

**Comment by mwahal** [comment]
Regarding the TWSPoller thread, I do like the idea and I have an enhancement request. I would like a callback to be called from the TWSPoller thread when the connection is lost and also when it's re-established. This is needed so that I can keep a flag when the connection is lost and then when its re-established I can clear the flag and use it to issue request executions, open orders, portfolio etc.

**Comment by Komnomnomnom** [comment]
Could you open a new issue for that @mwahal ?
