### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by isaklafleur** [Komnomnomnom/swigibpy#35]
I have tried to install swigibpy on Anaconda on both 32 and 64bit and can not build with MinGW on Windows 8.1 and 7.

I have tried to use Python 2.7.10, does not work either.

I have only been able to have it work on Python 32-bit 2.7.9 and it works great on both Windows 7 and 8.1.

**Comment by Komnomnomnom** [comment]
I've not had much experience building python extensions on windows as I almost exclusively work on linux but I remember having trouble building 64 bit extensions on windows previously (this was a couple of years ago though). 

If you post more information, especially, the build log and / or console output you are seeing I might be able to help further.

**Comment by Komnomnomnom** [comment]
One more thing, when building python extensions on windows try to ensure you are using the same compiler that built the Python exec / library you are using. i.e. if building for anaconda make sure to use the same compiler they did.

**Comment by isaklafleur** [comment]
Hello,

I decided to switch to Linux. It's works great on Linux!

Thank you,

Isak Engdahl

On Friday, June 12, 2015, Komnomnomnom <notifications@github.com> wrote:

> One more thing, when building python extensions on windows try to ensure
> you are using the same compiler that built the Python exec / library you
> are using. i.e. if building for anaconda make sure to use the same compiler
> they did.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Komnomnomnom/swigibpy/issues/35#issuecomment-111464418>
> .
>


-- 


Kind Regards
Isak Engdahl
