### ISSUE TITLE
Exception in run - swigibpy.py (version: 0.5.0)

### ISSUE THREAD

**Issue by mwahal** [Komnomnomnom/swigibpy#36]
Hi

From the setup.py file
======
IB_DIR = 'IB'
VERSION = '0.5.0'
=======

I am occasionally get an exception in run method. Here is the exception,

```python
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/swigibpy-0.5.0-py2.7-linux-x86_64.egg/swigibpy.py", line 2076, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```
Here is the code

```python
2072
2073             if fd > 0:
2074                 try:
2075                     evtin, evtout, evterr = select.select(pollfd, pollfd, pollfd, 1)
2076                 except select.error:
2077                     connected.clear()
2078                     continue
```

**Comment by Komnomnomnom** [comment]
hi @mwahal when does this occur? At shutdown / startup or in the middle of the execution of your program?

**Comment by mwahal** [comment]
Hi ..
Most of the time at shutdown, because I see that the IB transactions have finished (such as get execution reports etc).

Thanks
Mudit

**Comment by Komnomnomnom** [comment]
thanks @mwahal this looks like a well known issue caused by the Python interpeter clearing the module globals during shutdown before the thread has finished executing.

Although the error is safe to ignore I've just pushed some code to suppress it (cc9be027f14813548f06e4ac3b199322edacf0a3) to the master branch, could you try it out and let me know how it goes?

**Comment by mwahal** [comment]
I have patched both files, will let you know if I see them again.

**Comment by mwahal** [comment]
I have not seen the issue again. You can close this ddts now.

**Comment by Komnomnomnom** [comment]
Great thanks for the feedback
