### ISSUE TITLE
extremely high cpu usage?

### ISSUE THREAD

**Issue by kfir124** [Komnomnomnom/swigibpy#37]
Great project!
I've noticed that when swigibpy connects to TWS the python process is taking 99.4% cpu, even if nothing happens just sitting there connected to TWS cause it to drain most of the CPU power.

I am using Mac though I am not sure this should make a difference

using the latest swigibpy (0.5.0 right from github)

**seems like the auto_polling is the cause**
**setting poll_auto=False fixes the problem, probably a problem in the polling thread**

**Comment by kfir124** [comment]
the issue is with the main loop inside `TWSPoller`
inside the `run` method the outer loop will eat the cpu

I changed it to:
...
fd = tws.fd()
        pollfd = [fd]
        **import time**
        while not stop.is_set():
            **time.sleep(0.01)**
...
which fixed the problem completely, there is probably a more elegant way of doing it :)

**Comment by Komnomnomnom** [comment]
thanks @kfir124 it sounds like it has to do with the socket i/o. I'll look into it

**Comment by Komnomnomnom** [comment]
Just pushed a fix to master, please try it out and re-open if still an issue. The loop should not have been waiting on socket write.

**Comment by kfir124** [comment]
works great now thanks for the quick reply :)
