### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by leehanchung** [Komnomnomnom/swigibpy#40]
For the life of me I kept on getting error g++ failing with exit 1 after tons of warnings and a several "undefined reference to _head_C_build27_cpython_PCBuild_libpython27" from libs/libpython27.a.

Any help or suggestion on how to install for Windows will be much appreciated.

Also asked the same question http://stackoverflow.com/questions/34171177/swigibpy-windows-10-compile-error with the complete console log.

**Comment by Komnomnomnom** [comment]
Hmm I don't use windows but it looks like the problem is with MinGW and Python. Did you try building your own libpython27.a as described [here](http://stackoverflow.com/questions/32555087/unable-to-install-pyslalib-package-using-python2-7-mingw-on-windows-10)?

**Comment by leehanchung** [comment]
I figured its probably MinGW's linking problem with Python.  After trying to figure out what's wrong or what package to use all night, I threw my hands up, uninstall all PythonXY (Python 27), MinGW, VS15 from my Win10 box.  Reinstalled PythonXY and viola, swigibpy compiled.  

Will definitely save the link/info you've provided.  Thank you very much for the help!
