### ISSUE TITLE
Broken socket when using multiple EPosixClientSocket in different processes

### ISSUE THREAD

**Issue by CLevasseur** [Komnomnomnom/swigibpy#47]
We're getting an error when using multiple EPosixClientSocket in different processes: 

> 509: Exception caught while reading socket - Connection reset by peer

And a similar error is written in log files:

> [DH] INFO  [JTS-usfutureListenerS18-29710] - Disconnecting cdc1.ibllc.com:4000 with status DISCONNECT_ON_BROKEN_SOCKET

Its occurs as soon as some data are received from TWS. Everyting works fine if we execute pieces of code so that only one socket is used. Using `poll_auto=False` removes the error but since no other Poller is used, TWS messages are not handled. 

We use swigibpy 0.5.0 and TWS Build 956.2d

**Comment by Komnomnomnom** [comment]
Thanks @CLevasseur I haven't seen this before, do you have a small test case (code) that reproduces the bug?

**Comment by CLevasseur** [comment]
The bug was in our code, we gave the argument clientid instead of clientId to EPosixClientSocket.eConnect, and somehow we missed it during our tests, so every client used clientId 0 (default), so only the first socket could connect
