### ISSUE TITLE
auto reconnect parameter seems to raise error

### ISSUE THREAD

**Issue by smokersonly** [Komnomnomnom/swigibpy#48]
on macosx python 3.4 the parameter reconnect_auto=True seem to raise an error in the examples provided?

python historicaldata.py 
Traceback (most recent call last):
  File "historicaldata.py", line 72, in <module>
    tws = EPosixClientSocket(callback, reconnect_auto=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/swigibpy.py", line 1663, in **init**
    _swigibpy.EPosixClientSocket_swiginit(self,_swigibpy.new_EPosixClientSocket(_args, *_kwargs))
TypeError: new_EPosixClientSocket() takes at most 1 argument (2 given)

**Comment by smokersonly** [comment]
version 0.4.1 of swigibpy

**Comment by Komnomnomnom** [comment]
Thanks @smokersonly,  I think you might be using the examples from the latest master code with an older installed release (0.4.1) version of swigibpy. Either install the latest master code (by grabbing the code and installing it manually, i.e. not via pip) or use the examples from 0.4.1. (choose 0.4.1 in the tags / branches dropdown in github e.g. [historicaldata.py](https://github.com/Komnomnomnom/swigibpy/blob/0.4.1/examples/historicaldata.py)

Please re-open if you think there is still issue.
